sudo: true
dist: trusty
language: go
go:
  - '1.8' 

jobs:
  include:
    - stage: compile go app
      script: 
      - go get -d -v ./...
      - go build -v    
    - stage: build docker image
      script:
      - go get -d -v ./...
      - go build -v
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t vice-store:latest .
      - docker tag vice-store:latest viceregistry/vice-store:latest
      - docker images
      - docker push viceregistry/vice-store:latest
      
deploy:
  provider: releases
  api_key:
    secure: jctOjfd/8+8+7GUubcJHhYijS0mV7VGbdXGjt+uH1Azq1AnAxiqSfKtvNQ9qxKFuexcmTQzk6MZohsUZc5anmbPP/OzaO08JrmeR+PFyKINPqq3nqkI1uaADx/TUvUWrDJMZWgtMuypY11Q+ICfjaOko6gKOOWgS8LvU5cn1RTZcJx2LULD1t0lG+fLBoBcLsNgQhQHO6+gk+kClwo5F4fKRGHdyYBjNQs/z+08mi1bVurq9UhzQFeAviu4bTODZhKfzxu3EU3Jbl7HvmYwQ21O8yPyyMdfQgDO1FODlDh6bD0DvUMQQIAiKS3o6fJKQ9SqJSRfHo/C1lb5lhb1jd8cd3+JkI/4Y7wCA4zuW/AOQyX3MxIPyST+eDUQxWpEQCS16piYpzD8fz9YfU8hBnab3evjw+h7wkJ5S+F3oMM7oWqNfXD7EkMW/cGCtVWByxzOeAfnNWBhTP7UZWINwZHCOitpzUj2FikBToegkPiNljJejRtTYxnFWLclX70ht4VfK6UIbHxdr3dOADQ4B1C+D5woc6BeUC9p0TZOHhrca0mcvCpvuDZ+j6XricLS9etCNPlBJuZyMAcZi/azehfBH6C771d4JjfYTxLcmj4pMri9irbuThtzq2eMVheAm3ZLTnUR326bmOkwqUfYoGZOoZQFGK4GmRxzlOFxfzss=
  file: vice-store
  skip_cleanup: true
  on:
    repo: vice-registry/vice-store
    tags: true
